# Generated by Django 5.1.2 on 2024-10-29 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JOBSLISTING',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=500)),
                ('job_area', models.CharField(max_length=100)),
                ('job_pincode', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
