# Generated by Django 5.1.2 on 2024-10-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobslisting',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
